version: 0.2
phases:
  pre_build:
    commands:
      - echo Mule build-deployment phase initiated...
      - mvn test "-Dfile=mule-aws-poc/pom.xml"
  build:
    commands:
      - echo Build started on 'date'
      - mvn package
  post_build:
    commands:
      - echo Build completed on 'date'
      - mvn deploy -DmuleDeploy