version: 0.2
phases:
  pre_build:
    commands:
      - echo Mule build-deployment phase initiated...
      - cd mule-aws-poc
      - mvn test
  build:
    commands:
      - echo Build started on 'date'
      - mvn package
  post_build:
    commands:
      - echo Build completed on 'date'
      - mvn deploy -DmuleDeploy -Dcloud.env=Sandbox -Dcloudhub.workerType=Micro -DcloudhubAppName=mule-aws-poc-app -Dmule.version=4.2.2 -Dcloud.user=VamsiPallapothu -Dcloud.password=Miracle@2020